- name: Install NGINX
  hosts: localhost
  become: yes

  tasks:
    - name: Install latest version of Apache
      ansible.builtin.apt:
        name:
          - nginx
          - python3-boto3 # For the aws_s3 step
        state: present
        update_cache: yes

    - name: Get config file from s3
      aws_s3:
        bucket: imichka-ansible
        object: env/nat-instance/mastodon.conf
        dest: /etc/nginx/sites-available/mastodon.conf
        mode: get

    - name: Get config file from s3
      aws_s3:
        bucket: imichka-ansible
        object: env/nat-instance/files.conf
        dest: /etc/nginx/sites-available/files.conf
        mode: get

    - name: Link NGINX Reverse Proxy (mastodon subdomain)
      file:
        src: "/etc/nginx/sites-available/mastodon.conf"
        dest: "/etc/nginx/sites-enabled/mastodon.conf"
        state: link

    - name: Link NGINX Reverse Proxy (files subdomain)
      file:
        src: "/etc/nginx/sites-available/files.conf"
        dest: "/etc/nginx/sites-enabled/files.conf"
        state: link

    - name: Make Sure NGINX Service Is Running
      service:
        name: nginx
        state: restarted
        enabled: yes
