- name: Install Apache webserver for target
  hosts: all
  become: yes
 
  tasks:
    - name: Install apache httpd
      ansible.builtin.apt:
        name: apache2
        update_cache: yes
        state: present
 
    - name: Create index page for target
      ansible.builtin.copy:
        content: 'Hello world from target'
        dest: /var/www/html/index.html
