- name: Install Apache webserver for target
  hosts: localhost
  become: yes
 
  tasks:
    - name: Install latest version of Apache
      ansible.builtin.apt:
        name: apache2
        state: present
 
    - name: Create index page for target
      ansible.builtin.copy:
        content: 'Hello world from target'
        dest: /var/www/html/index.html

    - name: enabled mod_rewrite
      apache2_module: name=rewrite state=present
      notify:
        - restart apache2

  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted
